### ISSUE TITLE
cmake building with errors

### ISSUE THREAD

**Issue by garengllc** [gr-vt/gr-burst#4]
Fresh pull, create build directory, run cmake ../ from within it and get:
<<snip>>
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MAPPER_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /home/jason/gnuradio/gr-burst
   used as include directory in directory /home/jason/gnuradio/gr-burst/lib
   used as include directory in directory /home/jason/gnuradio/gr-burst/lib
   used as include directory in directory /home/jason/gnuradio/gr-burst/swig
   used as include directory in directory /home/jason/gnuradio/gr-burst/swig
   used as include directory in directory /home/jason/gnuradio/gr-burst/swig
   used as include directory in directory /home/jason/gnuradio/gr-burst/swig
   used as include directory in directory /home/jason/gnuradio/gr-burst/swig
   used as include directory in directory /home/jason/gnuradio/gr-burst/python
   used as include directory in directory /home/jason/gnuradio/gr-burst/apps
MAPPER_LIBRARIES (ADVANCED)
    linked by target "gnuradio-burst" in directory /home/jason/gnuradio/gr-burst/lib
    linked by target "test-burst" in directory /home/jason/gnuradio/gr-burst/lib
    linked by target "_burst_swig" in directory /home/jason/gnuradio/gr-burst/swig

-- Configuring incomplete, errors occurred!
See also "/home/jason/gnuradio/gr-burst/build/CMakeFiles/CMakeOutput.log".

**Comment by garengllc** [comment]
OK, I got it working.  I needed to install python-bitarray and build/install gr-mapper.  Might be good to list them in the front page README.

**Comment by greenoaktree** [comment]
I used old version ,new version of gr-burst is ok!
