### ISSUE TITLE
package 'mapper' not found when install gr-burst on ubuntu

### ISSUE THREAD

**Issue by greenoaktree** [gr-vt/gr-burst#5]
when I compile gr-burst ,there is an error :
-- checking for module 'mapper'
--   package 'mapper' not found
But I install gr-mapper alreadly,

When i open gr-fsk-burst/fsk-rx.grc 
there are two missing block:
burst_fsk_time_sync
burst_packer

the complete gr-burst cmake info is below

~/mysdr/gr-burst-master/build$ cmake ../
-- Build type not specified: defaulting to release.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
Checking for GNU Radio Module: RUNTIME
- INCLUDES=/usr/local/include
- LIBS=/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
  GNURADIO_RUNTIME_FOUND = TRUE
  Checking for GNU Radio Module: FILTER
- INCLUDES=/usr/local/include
- LIBS=/usr/local/lib/libgnuradio-filter.so;/usr/local/lib/libgnuradio-fft.so;/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
  GNURADIO_FILTER_FOUND = TRUE
  Checking for GNU Radio Module: VOLK
- INCLUDES=/usr/local/include
- LIBS=/usr/local/lib/libvolk.so
  GNURADIO_VOLK_FOUND = TRUE
  -- checking for module 'mapper'
  --   package 'mapper' not found
  -- Configuring done
  -- Generating done

**Comment by osh** [comment]
if you have installed gr-mapper in your prefix -- you probably need to set your CMAKE_INSTALL_PREFIX to the same thing for it to be able to find mapper.
